server.port: 5000
spring:
  jackson.serialization.indent_output: true

  # Configure webapp location
  resources.static-locations: file:./webapp/

  # Configure database connection
  datasource.url: jdbc:h2:./data/db
  jpa.hibernate.ddl-auto: update
  h2.console:
    enabled: true
    settings.web-allow-others: true

management:
  endpoint.shutdown.enabled: true
  endpoints:
    jmx.exposure.include: '*'
    web.exposure.include: '*'
